-- Qylo -- Phase 5 seed data: challenges for QT-M1..QT-M4
-- Generated from a content script; do not hand-edit the VALUES below.
-- Not idempotent by row identity (challenges have no natural unique key
-- to upsert on) -- guarded to only run once via a row-count check below.

do $$
begin
  if (select count(*) from public.challenges) = 0 then
    insert into public.challenges (module_code, difficulty, prompt, starter_data, grading_rule) values
      ('QT-M1', 'beginner', 'What does it mean for a qubit to be in superposition?', null, '{"type": "quiz", "options": ["It has two separate values, 0 and 1, stored as two independent bits", "It is described by two amplitudes at once, collapsing to one definite value only when measured", "It randomly switches between 0 and 1 every clock cycle", "It is undefined until a classical computer checks it"], "correct_index": 1}'::jsonb),
      ('QT-M1', 'beginner', 'What happens to a qubit''s superposition when you measure it?', null, '{"type": "quiz", "options": ["Nothing changes -- measuring it again can give a different random result", "It collapses to a definite classical value, and measuring it again immediately gives the same result", "It splits into two separate qubits", "Its amplitude values double"], "correct_index": 1}'::jsonb),
      ('QT-M1', 'beginner', 'Two qubits are in the entangled Bell state (|00⟩ + |11⟩)/√2. You measure the first qubit and get 0. What can you say about the second qubit?', null, '{"type": "quiz", "options": ["Nothing -- it''s completely independent of the first", "It must also be 0", "It must be 1", "It has a 25% chance of being 0"], "correct_index": 1}'::jsonb),
      ('QT-M1', 'beginner', 'Build a circuit that puts 1 qubit into an equal superposition of |0⟩ and |1⟩. (Hint: one gate is enough.)', '{"num_qubits": 1, "gates": []}'::jsonb, '{"type": "circuit", "num_qubits": 1, "expected_counts": {"0": 0.5, "1": 0.5}, "tolerance": 0.15}'::jsonb),
      ('QT-M2', 'beginner', 'In a circuit diagram, what does a solid dot on one wire connected by a vertical line to a ⊕ symbol on another wire represent?', null, '{"type": "quiz", "options": ["A measurement", "A CNOT gate -- the dot is the control qubit, the ⊕ is the target", "A barrier with no computational effect", "Two unrelated gates that happen to be drawn at the same position"], "correct_index": 1}'::jsonb),
      ('QT-M2', 'beginner', 'Which gate, applied to every qubit starting at |0⟩, creates an equal superposition of all 2^n basis states?', null, '{"type": "quiz", "options": ["X", "H (Hadamard)", "CNOT", "Z"], "correct_index": 1}'::jsonb),
      ('QT-M2', 'beginner', 'What does a dashed vertical line spanning multiple wires in a circuit diagram represent?', null, '{"type": "quiz", "options": ["A CNOT gate applied to every qubit it crosses", "A measurement of every qubit it crosses", "A barrier -- a purely visual/organizational marker with no computational effect", "A drawing error"], "correct_index": 2}'::jsonb),
      ('QT-M2', 'beginner', 'Build a Bell state: entangle 2 qubits so that measuring them gives "00" or "11" with roughly equal probability, and almost never "01" or "10".', '{"num_qubits": 2, "gates": []}'::jsonb, '{"type": "circuit", "num_qubits": 2, "expected_counts": {"00": 0.5, "11": 0.5}, "tolerance": 0.15}'::jsonb),
      ('QT-M3', 'intermediate', 'Using only one oracle query, what does the Deutsch-Jozsa algorithm determine about a function f?', null, '{"type": "quiz", "options": ["The exact output of f for every possible input", "Whether f is constant or balanced", "The prime factors of a number encoded by f", "The hidden period of f"], "correct_index": 1}'::jsonb),
      ('QT-M3', 'intermediate', 'What speedup does Grover''s algorithm provide for unstructured search over N items, compared to the best classical approach?', null, '{"type": "quiz", "options": ["An exponential speedup: roughly O(log N)", "No meaningful speedup", "A quadratic speedup: roughly O(√N)", "A cubic speedup: roughly O(N³)"], "correct_index": 2}'::jsonb),
      ('QT-M3', 'intermediate', 'Shor''s algorithm efficiently solves which problem, making it a real-world threat to RSA encryption?', null, '{"type": "quiz", "options": ["Sorting a large list", "Integer factorization, by reducing it to period-finding", "Graph coloring", "Matrix inversion"], "correct_index": 1}'::jsonb),
      ('QT-M4', 'advanced', 'In QAOA, what is the job of the "mixer" unitary layer?', null, '{"type": "quiz", "options": ["It encodes the optimization problem''s cost function as phase rotations", "It spreads amplitude back out across candidate answers so the search doesn''t get stuck on one", "It measures the final qubit states", "It classically evaluates how good a candidate solution is"], "correct_index": 1}'::jsonb),
      ('QT-M4', 'advanced', 'What does the variational principle guarantee about the energy VQE measures for any trial state?', null, '{"type": "quiz", "options": ["It always exactly equals the true ground state energy", "It is always greater than or equal to the true ground state energy -- never below", "It is always less than the true ground state energy", "It has no relationship to the true ground state energy"], "correct_index": 1}'::jsonb),
      ('QT-M4', 'advanced', 'What role does a classical computer play in the QAOA/VQE hybrid loop?', null, '{"type": "quiz", "options": ["None -- it''s a fully quantum algorithm end to end", "It only stores the final results", "It runs an optimizer that adjusts the circuit''s parameters based on what was measured", "It performs the actual quantum gate operations"], "correct_index": 2}'::jsonb);
  end if;
end $$;
